### PR TITLE
changed logo & menu

### LINKED ISSUE #3: Change the Menus and Add logo
**Brief description of the feature? Please describe.**
Change the Menus and Logo of the website similar to old website.

**Links and resources**
Link for the old website- [web](http://sheendeavors.org/)
Link for logo - [http://sheendeavors.org/images/logo-100.png](http://sheendeavors.org/images/logo-100.png)
**Screenshots for the new feature**
NA.
Please check old website.
**Additional Information**
NA

### PR DESCRIPTION
**Pull request by Manvityagi**
Fixed #3 
Changed the logo & the menu
image

> > > > @Manvityagi can you please share the screenshot? And yeah it's mandatory for every PR smile .
> > > 
> > > 
> > > ok!sure!
> > 
> > 
> > can you please remove container class from the navigation, margin issue ?
> 
> please increase the spacing between menu's. Also can we change the colour to #D428AC ?

okay!

### CODE REVIEW

**Comment by kindacoder** [comment]
@Manvityagi  can you please share the screenshot? And yeah it's mandatory for every PR :smile: .

**Comment by Manvityagi** [comment]
> @Manvityagi can you please share the screenshot? And yeah it's mandatory for every PR 😄 .

ok!sure!

**Comment by kindacoder** [comment]
> > @Manvityagi can you please share the screenshot? And yeah it's mandatory for every PR smile .
> 
> ok!sure!

can you please remove container class from the navigation, margin issue ?

**Comment by kindacoder** [comment]
> > > @Manvityagi can you please share the screenshot? And yeah it's mandatory for every PR smile .
> > 
> > 
> > ok!sure!
> 
> can you please remove container class from the navigation, margin issue ?

please increase the spacing between menu's. Also can we change the colour to #D428AC ?

**Comment by Manvityagi** [comment]
> > > > @Manvityagi can you please share the screenshot? And yeah it's mandatory for every PR smile .
> > > 
> > > 
> > > ok!sure!
> > 
> > 
> > can you please remove container class from the navigation, margin issue ?
> 
> please increase the spacing between menu's. Also can we change the colour to #D428AC ?


> > > > @Manvityagi can you please share the screenshot? And yeah it's mandatory for every PR smile .
> > > 
> > > 
> > > ok!sure!
> > 
> > 
> > can you please remove container class from the navigation, margin issue ?
> 
> please increase the spacing between menu's. Also can we change the colour to #D428AC ?



> > > > @Manvityagi can you please share the screenshot? And yeah it's mandatory for every PR smile .
> > > 
> > > 
> > > ok!sure!
> > 
> > 
> > can you please remove container class from the navigation, margin issue ?
> 
> please increase the spacing between menu's. Also can we change the colour to #D428AC ?

please check the ss on slack once.

**Comment by Manvityagi** [comment]
I have done the suggested changes @kindacoder.

**Pull request merged**
