### PR TITLE
Develop author details page #6

### LINKED ISSUE #6: Develop author details page
**Brief description of the feature? Please describe.**
In this issue, write story page need to be developed. write story page contains -

- Trending stories (right corner )
- bookmark story 
- total no of shares
- share story
- story details
- author details
- comments

**Links and resources**
[link to the wireframe](http://bit.ly/she-author-page)
**Screenshots for the new feature**
[screenshot](http://bit.ly/she-author-page)

**Additional Information**
NA

### PR DESCRIPTION
**Pull request by asha15**
@kindacoder @prithaupadhyay  Fixed #6 

Screenshot (11)
Screenshot (8)

### CODE REVIEW

**Review by prithaupadhyay — CHANGES_REQUESTED** [review]
Good Work @asha15 . Needs a few improvements.
1. With drop down, the screen is sliding horizontally. Fix the horizontal width.
2. There is no proper left margin. The Add To section breaks the margin. Please match it with the provided mockup.
3. No comments section
Try to have all the sections as provided in the mockup

**Comment by asha15** [comment]
@prithaupadhyay  in the mockup, i feel little bit difficult to see the bottom part of it. i'll appreciate if you help me by posting  a screenshot.

**Comment by prithaupadhyay** [comment]
@asha15  I have attached the wireframes for the Author Details Page.
image
image
image

**Comment by asha15** [comment]
@prithaupadhyay  thank you

**Comment by asha15** [comment]
@prithaupadhyay Updated the changes. 

Screenshot (73)
Screenshot (74)
Screenshot (75)

**Comment by prithaupadhyay** [comment]
@asha15 Please check your slack DM.

**Pull request closed without merging**
