### PR TITLE
Update to get-inspired.css

### PR DESCRIPTION
**Pull request by rsvarma95**
Update to get-inspired.css to prevent cards from overlapping

### CODE REVIEW

**Comment by rsvarma95** [comment]
Referencing issue #22

**Comment by kindacoder** [comment]
can you please share the screenshots @Raul9595 ?

**Comment by rsvarma95** [comment]
Here are the screenshots in two different browsers for the _get_inspired.html_ page.

**Mozilla Firefox :** 

image
image

**Microsoft Edge :**

image
image

**Google Chrome :**

image
image

**Comment by kindacoder** [comment]
What about the mobile responsiveness ?

**Comment by rsvarma95** [comment]
I have included the mobile screenshots below : 

**Google Pixel 2 :**

image
image

**IPhone 6/7/8 Plus :**

image
image

**Comment by kindacoder** [comment]
can we work on spacing ?
Also can we do some styling in categories ? 3 cat per line or something like that. ?
The font for heading _Trending stories_ , we can work on this one too.

**Comment by rsvarma95** [comment]
Ok sure. I didnt want to touch the other parts of the code since I thought I should restrict myself to fixing the issue mentiones. Anyways I'll look into the above points.

**Comment by kindacoder** [comment]
> Ok sure. I didnt want to touch the other parts of the code since I thought I should restrict myself to fixing the issue mentiones. Anyways I'll look into the above points.

No issue. Thanks for that we can create new issue for that. :+1:

**Comment by kindacoder** [comment]
> > Ok sure. I didnt want to touch the other parts of the code since I thought I should restrict myself to fixing the issue mentiones. Anyways I'll look into the above points.
> 
> No issue. Thanks for that we can create new issue for that.

Please create a new issue of easy difficulty level and work on that one. I'm merging this one.

**Pull request merged**
