### PR TITLE
Login page(HTML and CSS)

### PR DESCRIPTION
**Pull request by palak2001**

### CODE REVIEW

**Comment by prithaupadhyay** [comment]
@palak2001 Please provide a description along with an image of your work here.

**Comment by palak2001** [comment]
I have made a login page which will interact with user and will ask its username and password with a button of Login(Front-end)

**Comment by palak2001** [comment]
Login Page

**Comment by kindacoder** [comment]
@palak2001  isn't is looking a bit different from other pages ?can't we work on colours and backgrounds  for this page ?

**Comment by palak2001** [comment]
[Login.zip](https://github.com/she-endeavors/SheE/files/3114339/Login.zip)
I tried my best to change the fonts accordingly taking care the best duit to login page

**Comment by palak2001** [comment]
image

**Pull request closed without merging**
