### PR TITLE
add author-story page

### LINKED ISSUE #10: Author's story page
**Brief description of the feature? Please describe.**
Author's story  page.
**Links and resources**
[https://adobe.ly/2FIRXnx](https://adobe.ly/2FIRXnx)
**Screenshots for the new feature**
[https://adobe.ly/2FIRXnx](https://adobe.ly/2FIRXnx)
**Additional Information**
NA

### PR DESCRIPTION
**Pull request by vaibhav-sharma-frontend**
Add author-story page i.e. both author-story.html and author-story.css
Issue Fixed #10
Screenshot from 2019-05-10 00-18-57
Screenshot from 2019-05-10 00-19-02

### CODE REVIEW

**Comment by vaibhav-sharma-frontend** [comment]
@prithaupadhyay @kindacoder plz review my PR.
:man_technologist:

**Review by prithaupadhyay — CHANGES_REQUESTED** [review]
Good Work @vsharma20v . Just make the lower boundary of the story container box visible, so that the end does not look abrupt. Rest looks fine.

**Comment by vaibhav-sharma-frontend** [comment]
> Good Work @vsharma20v . Just make the lower boundary of the story container box visible, so that the end does not look abrupt. Rest looks fine.

@prithaupadhyay Done

**Comment by prithaupadhyay** [comment]
@vsharma20v Please attach a Screenshot whenever you make any kind of change.

**Comment by vaibhav-sharma-frontend** [comment]
Screenshots:
Screenshot from 2019-05-10 13-36-49
Screenshot from 2019-05-10 13-36-51

**Comment by prithaupadhyay** [comment]
Good Work @vsharma20v . Work looks good to me. @kindacoder Please have a look at it. Its good to merge from my side.

**Pull request merged**
