### PR TITLE
Develop a HTML and CSS page for All Stories

### LINKED ISSUE #14: Develop an HTML page for "All Stories"
### Brief description of the feature? 
You need to develop an HTML page for "All Stories" section, where all the stories will be displayed separated by their categories. Use Bootstrap for implementing the design. 
You need to refer to the designed mockup, as mentioned below.
### Links and resources
[Wireframe](https://xd.adobe.com/view/da8357fa-7130-4652-8f5b-161ee246a39e/)
#### Mockup
web_1920_____1-1

### PR DESCRIPTION
**Pull request by vaibhav-sharma-frontend**
Issue Fixed #14 
Screenshot from 2019-04-17 16-02-02
Screenshot from 2019-04-17 16-02-13

### CODE REVIEW

**Review by prithaupadhyay — COMMENTED** [review]
@vsharma20v Great work ! 
Just work a bit on the responsiveness and it will be good to merge.

**Comment by vaibhav-sharma-frontend** [comment]
> @vsharma20v Great work !
> Just work a bit on the responsiveness and it will be good to merge.

Do I need to make mobile view of it also?

**Comment by prithaupadhyay** [comment]
@vsharma20v It is not only about mobile view, but it is always good to have a responsive site suitable for all screen sizes.

**Comment by vaibhav-sharma-frontend** [comment]
> @vsharma20v It is not only about the mobile view, but it is always good to have a responsive site suitable for all screen sizes.

Can you share the mobile mockup or can u tell me how it should be going to look at smaller width i.e. where trending stories section goes and also about all stories.

**Comment by vaibhav-sharma-frontend** [comment]
Add responsiveness in get-inspired page

**screenshots:**

Screenshot from 2019-04-21 19-33-25
Screenshot from 2019-04-21 19-33-44
Screenshot from 2019-04-21 19-33-48

**Comment by vaibhav-sharma-frontend** [comment]
@prithaupadhyay @kindacoder now review the updated PR

**Review by prithaupadhyay — APPROVED** [review]
LGTM 👍. @kindacoder  Please do have a look

**Pull request merged**
